export const FETCH_MOVIES = 'FETCH_MOVIES'
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST'
export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST'
export const RATE_MOVIE = 'RATE_MOVIE'
export const FETCH_MORE_MOVIES = "FETCH_MORE_MOVIES"
export const SEARCH_MOVIES = "SEARCH_MOVIES"